import re
import unittest
from pathlib import Path


class StudioUiTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.html = Path(__file__).with_name("logitrack_studio.html").read_text(encoding="utf-8")
        cls.python_source = Path(__file__).with_name("LogiTrackRC v4.4.py").read_text(encoding="utf-8")

    def test_login_first_shell_and_app_shell_present(self):
        self.assertIn('id="loginShell"', self.html)
        self.assertIn('id="appShell"', self.html)
        self.assertIn("Sign in to RC Atlas", self.html)
        self.assertIn('placeholder="name@organization.org"', self.html)
        self.assertIn("RC Atlas", self.html)
        self.assertIn("Operational Intelligence Workspace", self.html)
        self.assertIn("Portfolio Overview", self.html)
        self.assertIn("Organization Administration", self.html)

    def test_public_login_shell_hides_operational_kpis(self):
        login_shell = self.html.split('id="loginShell"', 1)[1].split('id="appShell"', 1)[0]
        self.assertIn("RC Atlas", login_shell)
        self.assertIn("Operational Intelligence Workspace", login_shell)
        self.assertIn("Workspace shell", login_shell)
        self.assertIn('id="developerToolsSummary"', login_shell)
        self.assertNotIn("LogiTrack Studio", login_shell)
        self.assertNotIn("Portfolio command view", login_shell)
        self.assertNotIn("Portfolio delivery", login_shell)
        self.assertNotIn("Reporting confidence", login_shell)
        self.assertNotIn("Escalations", login_shell)
        self.assertNotIn("Implementation momentum", login_shell)
        self.assertNotIn("Donor readiness", login_shell)
        self.assertNotIn("preview-kpi-grid", login_shell)
        self.assertNotIn("preview-rows", login_shell)

    def test_safe_frontend_helpers_present(self):
        self.assertIn("function asArray", self.html)
        self.assertIn("function joinSafe", self.html)
        self.assertIn("function textSafe", self.html)
        self.assertNotIn("(item.linked_indicator_ids || []).join", self.html)
        self.assertIn('joinSafe(item.linked_indicator_ids, ", ", "-")', self.html)

    def test_status_localization_layer_present(self):
        self.assertIn('id="uiLanguagePicker"', self.html)
        self.assertIn("const UI_STRINGS", self.html)
        self.assertIn("function applyStaticLocalization", self.html)
        self.assertIn("function translateRichText", self.html)
        self.assertIn("const STATUS_LABELS", self.html)
        self.assertIn('"VERMELHO": "RED"', self.html)
        self.assertIn('"SUPEROU": "EXCEEDED"', self.html)
        self.assertIn("function localizeStatusLabel", self.html)
        self.assertIn("function localizeInlineStatusText", self.html)
        self.assertIn("function localizeSeverityLabel", self.html)
        self.assertIn("function localizeAudienceValue", self.html)
        self.assertIn('"auth.hero.title": "Operational Intelligence Workspace"', self.html)
        self.assertIn('"auth.hero.copy": "Centralize supervisao operacional, reporting, coordenacao e inteligencia de entrega num unico workspace seguro."', self.html)
        self.assertIn('"auth.outcome_4": "Operational visibility"', self.html)
        self.assertIn('"auth.outcome_4": "Visibilidade operacional"', self.html)

    def test_canonical_status_helper_present_and_safe(self):
        self.assertIn("function canonicalStatus(value, fallback = \"SEM DADOS\")", self.html)
        self.assertIn("return canonical || normalizeStatusKey(fallback) || \"SEM DADOS\";", self.html)
        self.assertIn('const key = canonicalStatus(item.status || item.status_weighted_canon || item.status_mean_canon || "SEM DADOS");', self.html)
        self.assertIn('const status = canonicalStatus(item.status || "SEM DADOS");', self.html)
        self.assertIn('"NO DATA": "SEM DADOS"', self.html)
        self.assertIn('"RED": "VERMELHO"', self.html)
        self.assertIn('"GREEN": "VERDE"', self.html)

    def test_professional_status_color_system_present(self):
        self.assertIn("--status-red", self.html)
        self.assertIn("--status-yellow", self.html)
        self.assertIn("--status-green", self.html)
        self.assertIn("--status-exceeded", self.html)
        self.assertIn("--status-neutral", self.html)
        self.assertIn("function segmentMeta", self.html)
        self.assertIn("statusClassName(", self.html)

    def test_favicon_is_configured(self):
        self.assertIn('rel="icon"', self.html)
        self.assertIn('@app.get("/favicon.ico")', self.python_source)

    def test_operational_access_messages_are_humanized(self):
        self.assertIn("This area is not part of your operational responsibilities.", self.html)
        self.assertIn("Administration tools are reserved for organization governance responsibilities.", self.html)
        self.assertIn("Notification rule management is not part of this role's workspace.", self.html)
        self.assertIn("Task assignment is handled from a coordination role in this workspace.", self.html)
        self.assertNotIn("Current session does not have permission for this resource.", self.html)
        self.assertNotIn("Current session does not have permission for one or more admin resources.", self.html)
        self.assertNotIn("Protected notification rules require an authenticated analyst or admin session.", self.html)
        self.assertNotIn("The current permission set cannot assign new operational tasks.", self.html)
        self.assertNotIn("Task creation is restricted by workspace permissions.", self.html)

    def test_structured_quality_and_mapping_views_present(self):
        self.assertIn('id="mappingSummaryCards"', self.html)
        self.assertIn('id="mappingConfidenceBox"', self.html)
        self.assertIn('id="mappingTableBody"', self.html)
        self.assertIn('id="qualitySummaryCards"', self.html)
        self.assertIn('id="qualityInterpretationBox"', self.html)
        self.assertIn('id="qualityIssueSummary"', self.html)
        self.assertIn('id="qualityTableBody"', self.html)
        self.assertIn('id="datasetNarrativeSummary"', self.html)
        self.assertIn('id="datasetNarrativeInsights"', self.html)
        self.assertIn('class="technical-details"', self.html)

    def test_live_language_rerender_support_present(self):
        self.assertIn("function rerenderLocalizedViews", self.html)
        self.assertIn("renderSemanticMapping(state.datasetMapping)", self.html)
        self.assertIn("renderQualityReport(state.datasetQualityReport)", self.html)
        self.assertIn("renderDatasetNarrativePanel(state.datasetNarrative)", self.html)
        self.assertIn("window.localStorage.setItem(\"logitrack.uiLanguage\"", self.html)

    def test_session_persistence_and_multi_org_auth_shell_present(self):
        self.assertIn('const AUTH_TOKEN_STORAGE_KEY = "rcatlas.authToken";', self.html)
        self.assertIn('const SESSION_USER_STORAGE_KEY = "rcatlas.sessionUser";', self.html)
        self.assertIn("function persistSessionState()", self.html)
        self.assertIn("function clearPersistedSessionState()", self.html)
        self.assertIn("function restorePersistedSessionState()", self.html)
        self.assertIn('payload = {', self.html)
        self.assertIn('email: document.getElementById("bootstrapUsername").value.trim(),', self.html)
        self.assertIn('organization_name: state.workspace?.organization?.organization_name || "Blue Delta Consortium",', self.html)
        self.assertIn('role: "organization_admin",', self.html)
        self.assertIn('state.currentUser.organization_name', self.html)

    def test_presentation_mode_and_login_productization_present(self):
        self.assertIn('id="presentationModeBtn"', self.html)
        self.assertIn('id="splashScreen"', self.html)
        self.assertIn('id="presentationDeck"', self.html)
        self.assertIn('id="presentationPrevBtn"', self.html)
        self.assertIn('id="presentationNextBtn"', self.html)
        self.assertIn("function applyPresentationMode", self.html)
        self.assertIn("function setPresentationMode", self.html)
        self.assertIn("function renderPresentationDeck", self.html)
        self.assertIn("function changePresentationSlide", self.html)
        self.assertIn("function dismissSplash", self.html)
        self.assertIn('id="developerToolsSummary"', self.html)
        self.assertIn('id="loginOutcome1"', self.html)
        self.assertIn('id="loginOutcome4"', self.html)
        self.assertIn('id="loginHelpBox"', self.html)
        self.assertIn('id="loginLanguagePicker"', self.html)
        self.assertIn('"auth.login_help"', self.html)
        self.assertIn("button.presentation_mode", self.html)
        self.assertIn("presentationMode: false,", self.html)
        self.assertNotIn('presentationMode: window.localStorage.getItem("logitrack.presentationMode") === "true"', self.html)
        self.assertNotIn("LogiTrack Studio", self.html)

    def test_intelligence_storytelling_and_visual_recommendation_present(self):
        self.assertIn("function buildPortfolioBriefing", self.html)
        self.assertIn("function buildProjectBriefing", self.html)
        self.assertIn("function compactBriefingHtml", self.html)
        self.assertIn("function strongestBriefingSection", self.html)
        self.assertIn("function buildIndicatorAnalyticsModel", self.html)
        self.assertIn("function renderIndicatorIntelligence", self.html)
        self.assertIn("function buildSemanticVisualRecommendations", self.html)
        self.assertIn("function microSparklineSvg", self.html)
        self.assertIn("function alertCardHtml", self.html)
        self.assertIn("function renderComparisonBars", self.html)
        self.assertIn("function renderHeatIndicators", self.html)
        self.assertIn("function renderAlertDistribution", self.html)
        self.assertIn("function renderRegionalComparison", self.html)
        self.assertIn("Project footprint and context", self.html)
        self.assertIn("More insight", self.html)
        self.assertIn("Expand Executive Briefing", self.html)
        self.assertIn("Top operational alerts", self.html)

    def test_operational_visual_refinement_helpers_present(self):
        self.assertIn("function formatDateForUi", self.html)
        self.assertIn("function freshnessLabel", self.html)
        self.assertIn("function daysSinceDate", self.html)
        self.assertIn("function renderWorkplanTimeline", self.html)
        self.assertIn("function renderOverviewCommandHeader", self.html)
        self.assertIn("function buildPortfolioOverviewMetrics", self.html)
        self.assertIn("function renderPortfolioPulse", self.html)
        self.assertIn("function renderPortfolioGeoCoverage", self.html)
        self.assertIn("function renderPortfolioSectorPerformance", self.html)
        self.assertIn("function renderPortfolioBudgetAlignment", self.html)
        self.assertIn("function renderPortfolioStatusBreakdown", self.html)
        self.assertIn("function renderPortfolioOverdueTasks", self.html)
        self.assertIn("function renderOverviewExecutiveSignals", self.html)
        self.assertIn("function coverageMapSvg", self.html)
        self.assertIn("function renderBudgetDeliveryColumns", self.html)
        self.assertIn("function renderRankedProgressList", self.html)
        self.assertIn("function buildOverviewContextBadges", self.html)
        self.assertIn("Delivery Health", self.html)
        self.assertIn("Delivery Health Over Time", self.html)
        self.assertIn("Implementation Footprint", self.html)
        self.assertIn("Sector Delivery Performance", self.html)
        self.assertIn("Budget vs Delivery", self.html)
        self.assertIn("Implementation Status", self.html)
        self.assertIn("Top Overdue Tasks", self.html)
        self.assertIn("function miniAreaChart", self.html)
        self.assertIn("function miniBarTrend", self.html)
        self.assertIn("function progressArc", self.html)
        self.assertIn("function confidenceGauge", self.html)
        self.assertIn("function distributionStack", self.html)
        self.assertIn("function radialHealthGauge", self.html)
        self.assertIn("function visualInterpretationForChart", self.html)
        self.assertIn("function wrapVisualShell", self.html)
        self.assertIn("Operational interpretation", self.html)
        self.assertIn("async function openProjectView", self.html)
        self.assertIn("event.preventDefault();", self.html)
        self.assertIn("if (!state.workspace) {", self.html)
        self.assertIn("if (!state.projectSnapshot) {", self.html)

    def test_operational_semantics_helpers_present(self):
        self.assertIn("function operationalStatusLegendLabel", self.html)
        self.assertIn("function contextualEmptyState", self.html)
        self.assertIn("function comparisonToneClass", self.html)
        self.assertIn("function comparisonNarrative", self.html)
        self.assertIn("function operationalNarrativeText", self.html)
        self.assertIn("function humanizeChartTypeLabel", self.html)
        self.assertIn("function humanizeWidgetSection", self.html)
        self.assertIn("function semanticCategoryLabel", self.html)
        self.assertIn("Critical delivery exposure", self.html)
        self.assertIn("Watchlist delivery areas", self.html)
        self.assertIn("Operationally stable areas", self.html)
        self.assertIn("Reporting inputs pending validation", self.html)
        self.assertIn("Geographic Coverage", self.html)
        self.assertIn("Escalation Exposure", self.html)
        self.assertIn("Operational analysis", self.html)
        self.assertIn("critical delivery threshold", self.html)
        self.assertIn('renderDonut(content.segments || [], { context: "status_donut" })', self.html)
        self.assertIn('renderComparisonBars(derived, chartType === "budget_delivery_comparison" ? "Budget benchmark" : "Target", {', self.html)
        self.assertIn('class="regional-card-status ${tone}"', self.html)
        self.assertIn("Negative delivery variance requires immediate management attention.", self.html)

    def test_workspace_hydration_renderers_are_present(self):
        self.assertIn("renderOverviewCommandHeader(workspace);", self.html)
        self.assertIn("renderOverviewCards(workspace);", self.html)
        self.assertIn("renderPortfolioNarrative(workspace?.narrative || {});", self.html)
        self.assertIn("renderOverviewExecutiveSignals(workspace);", self.html)
        self.assertIn("renderPortfolioPulse(workspace);", self.html)
        self.assertIn("renderPortfolioGeoCoverage(workspace);", self.html)
        self.assertIn("renderPortfolioSectorPerformance(workspace);", self.html)
        self.assertIn("renderPortfolioBudgetAlignment(workspace);", self.html)
        self.assertIn("renderPortfolioStatusBreakdown(workspace);", self.html)
        self.assertIn("renderPortfolioOverdueTasks(workspace);", self.html)
        self.assertIn("renderOverviewNotifications(workspace?.notifications || []);", self.html)
        self.assertNotIn("canonicalStatus is not defined", self.html)
        self.assertIn('id="overviewContextHeader"', self.html)
        self.assertIn('id="portfolioGeoCoverage"', self.html)
        self.assertIn('id="overviewSectorPerformanceBox"', self.html)
        self.assertIn('id="overviewBudgetAlignmentBox"', self.html)
        self.assertIn('id="overviewImplementationStatusBox"', self.html)
        self.assertIn('id="overviewOverdueTasksBox"', self.html)
        self.assertIn('id="overviewExecutiveSignals"', self.html)
        self.assertIn('class="overview-band-grid"', self.html)
        self.assertIn('class="overview-focus-grid"', self.html)
        self.assertIn('class="overview-secondary-grid"', self.html)
        self.assertIn('class="overview-stage"', self.html)
        self.assertIn("overview-portfolio-drawer", self.html)
        self.assertIn("async function runOverviewAction(action)", self.html)
        self.assertIn('data-overview-action="overview-indicators"', self.html)
        self.assertEqual(self.html.count('id="overviewNotificationList"'), 1)

    def test_project_executive_command_surface_present(self):
        self.assertIn('id="executiveCommandTitle"', self.html)
        self.assertIn('id="executiveLead"', self.html)
        self.assertIn('id="projectInsightBoard"', self.html)
        self.assertIn('id="projectExecutiveAlerts"', self.html)
        self.assertIn('id="projectCoordinationBox"', self.html)
        self.assertIn('id="projectCoverageFootprint"', self.html)
        self.assertIn('id="projectExecutiveNarrative"', self.html)
        self.assertIn('id="executiveDashboardTitle"', self.html)
        self.assertIn("function preferredProjectTemplateId", self.html)
        self.assertIn("function buildProjectExecutiveModel", self.html)
        self.assertIn("function renderProjectInsightBoard", self.html)
        self.assertIn("function renderProjectExecutiveAlerts", self.html)
        self.assertIn("function renderProjectCoordination", self.html)
        self.assertIn("function renderProjectCoverageFootprint", self.html)
        self.assertIn("state.templateId = preferredProjectTemplateId(workspace.templates);", self.html)
        self.assertIn("renderProjectInsightBoard(snapshot);", self.html)
        self.assertIn('renderProjectExecutiveAlerts(snapshot, canViewRisks ? risks : { items: [] });', self.html)
        self.assertIn('renderProjectCoordination(canViewWorkplan ? workplan : null, snapshot);', self.html)
        self.assertIn("renderProjectCoverageFootprint(snapshot);", self.html)
        self.assertIn('id="openNarrativeFromExecutiveBtn"', self.html)

    def test_project_executive_narrative_dual_render_present(self):
        self.assertIn('document.getElementById("projectNarrativeDetail").innerHTML = html;', self.html)
        self.assertIn('const executiveBox = document.getElementById("projectExecutiveNarrative");', self.html)
        self.assertIn('if (executiveBox) executiveBox.innerHTML = html;', self.html)

    def test_indicator_intelligence_view_and_navigation_present(self):
        self.assertIn('data-view="indicator-intelligence"', self.html)
        self.assertIn('id="indicatorPicker"', self.html)
        self.assertIn('id="indicatorHero"', self.html)
        self.assertIn('id="indicatorVisualGrid"', self.html)
        self.assertIn('id="indicatorInsightSummary"', self.html)
        self.assertIn('button class="nav-link" data-view="indicator-intelligence"', self.html)
        self.assertIn("Why This Is Happening", self.html)
        self.assertIn("What Needs Attention", self.html)
        self.assertIn("function indicatorPrimaryNarrative", self.html)
        self.assertIn("function indicatorBudgetSummary", self.html)
        self.assertIn("function indicatorReadinessSummary", self.html)
        self.assertIn("function buildIndicatorActions", self.html)
        self.assertIn("function indicatorLegendChip", self.html)
        self.assertIn("District performance ranking", self.html)
        self.assertIn("Budget vs delivery reality", self.html)
        self.assertIn("Operational posture", self.html)
        self.assertIn("Management action", self.html)

    def test_operational_coordination_engine_present(self):
        self.assertIn('id="roleFocusBox"', self.html)
        self.assertIn('id="taskBoardBox"', self.html)
        self.assertIn('id="taskWorkflowList"', self.html)
        self.assertIn('id="workplanFeedList"', self.html)
        self.assertIn('id="taskComposerAccessNote"', self.html)
        self.assertIn('id="createTaskBtn"', self.html)
        self.assertIn('id="homeRoleExperienceBox"', self.html)
        self.assertIn('id="homeInboxSummary"', self.html)
        self.assertIn('id="myWorkInboxList"', self.html)
        self.assertIn('id="homeOperationalPulse"', self.html)
        self.assertIn('id="homeActivityFeedList"', self.html)
        self.assertIn('id="notificationSummaryCards"', self.html)
        self.assertIn('id="notificationActionQueue"', self.html)
        self.assertIn('id="notificationContextGroups"', self.html)
        self.assertIn('id="taskDrawerShell"', self.html)
        self.assertIn('id="taskDrawerBackdrop"', self.html)
        self.assertIn('id="taskDrawerPanel"', self.html)
        self.assertIn('id="taskDrawerContent"', self.html)
        self.assertIn("function currentOperationalProfile", self.html)
        self.assertIn("function currentTaskRows", self.html)
        self.assertIn("function findTaskRecord", self.html)
        self.assertIn("function buildOperationalInboxItems", self.html)
        self.assertIn("function renderHomeOperationalExperience", self.html)
        self.assertIn("function renderNotificationCenter", self.html)
        self.assertIn("function openTaskDrawer", self.html)
        self.assertIn("function closeTaskDrawer", self.html)
        self.assertIn("function renderTaskDrawer", self.html)
        self.assertIn("function syncTaskComposerAccess", self.html)
        self.assertIn("function renderTaskBoardSummary", self.html)
        self.assertIn("function renderTaskWorkflowList", self.html)
        self.assertIn("function renderOperationalActivityFeed", self.html)
        self.assertIn("function taskMutationPayload", self.html)
        self.assertIn("function handleTaskWorkflowAction", self.html)
        self.assertIn("function createOperationalTaskFromForm", self.html)
        self.assertIn('/v1/demo/tasks/${encodeURIComponent(taskId)}/update', self.html)
        self.assertIn('/v1/demo/tasks/${encodeURIComponent(taskId)}/validate', self.html)
        self.assertIn('await callApi("/v1/demo/tasks", {', self.html)
        self.assertIn('document.getElementById("createTaskBtn").addEventListener("click", createOperationalTaskFromForm);', self.html)
        self.assertIn('document.getElementById("myWorkInboxList").addEventListener("click", event => {', self.html)
        self.assertIn('document.getElementById("taskWorkflowList").addEventListener("click", event => {', self.html)
        self.assertIn('document.getElementById("taskDrawerCloseBtn").addEventListener("click", closeTaskDrawer);', self.html)
        self.assertIn('document.getElementById("taskDrawerBackdrop").addEventListener("click", closeTaskDrawer);', self.html)
        self.assertIn('data-task-open="${textSafe(task.task_id)}"', self.html)
        self.assertIn('data-inbox-view=', self.html)
        self.assertIn("Operational Coordination Engine", self.html)
        self.assertIn("Operational Activity Feed", self.html)

    def test_demo_role_switcher_present(self):
        self.assertIn('id="demoRoleSwitcherBar"', self.html)
        self.assertIn('id="roleSwitcherTitle"', self.html)
        self.assertIn('id="roleSwitcherNote"', self.html)
        self.assertIn('id="roleSwitcherButtons"', self.html)
        self.assertIn("roleContext: null,", self.html)
        self.assertIn('const OPERATIONAL_ROLE_IDS = ["organization_admin", "programme_manager", "meal_officer", "field_coordinator", "executive_viewer"];', self.html)
        self.assertIn('const DEFAULT_OPERATIONAL_ROLE_ID = "programme_manager";', self.html)
        self.assertIn("function normalizeOperationalRoleId", self.html)
        self.assertIn("function operationalRoleProfileById", self.html)
        self.assertIn("function sessionOperationalRoleId", self.html)
        self.assertIn("function buildRoleContext", self.html)
        self.assertIn("function syncRoleContext", self.html)
        self.assertIn("function currentRoleContext", self.html)
        self.assertIn("function currentRoleView", self.html)
        self.assertIn("function currentRoleIdentity", self.html)
        self.assertIn("function rolePerspectiveSummary", self.html)
        self.assertIn("function roleFilteredNotifications", self.html)
        self.assertIn("function setDemoRoleOverride", self.html)
        self.assertIn("function renderDemoRoleSwitcher", self.html)
        self.assertIn('window.localStorage.getItem("logitrack.demoRoleOverride")', self.html)
        self.assertIn('syncRoleContext({ persist: false });', self.html)
        self.assertIn('const roleSimulationVisible = Boolean(state.currentUser) && state.currentView === "studio-lab";', self.html)
        self.assertIn('document.getElementById("roleSwitcherButtons").addEventListener("click", event => {', self.html)
        self.assertIn('data-demo-role="${roleId}"', self.html)
        self.assertIn('const roleView = currentRoleView(profile.id);', self.html)
        self.assertIn("Organization Admin", self.html)
        self.assertIn("Programme Manager", self.html)
        self.assertIn("MEAL Officer", self.html)
        self.assertIn("Field Coordinator", self.html)
        self.assertIn("Executive Viewer", self.html)

    def test_role_centric_workspace_helpers_present(self):
        self.assertIn("function roleNavigationBlueprint", self.html)
        self.assertIn("function adaptiveNavigationItems", self.html)
        self.assertIn("function defaultNavSectionForView", self.html)
        self.assertIn("function roleWorkspaceHasView", self.html)
        self.assertIn("function roleAwareViewMeta", self.html)
        self.assertIn("function syncAuthenticatedRoleLanding", self.html)
        self.assertIn("function buildAdminGovernanceModel", self.html)
        self.assertIn("function overviewChromeModel", self.html)
        self.assertIn("function applyRoleCentricOverviewChrome", self.html)
        self.assertIn("function tasksForRoleWorkspace", self.html)
        self.assertIn("function operationalBoundaryMessage", self.html)
        self.assertIn("const allowed = adaptiveNavigationItems(roleId, permissionIds);", self.html)
        self.assertIn("Governance Inbox", self.html)
        self.assertIn("Validation Inbox", self.html)
        self.assertIn("My Assigned Work", self.html)
        self.assertIn("Strategic Attention", self.html)
        self.assertIn("Users & Roles", self.html)
        self.assertIn("Audit Log", self.html)

    def test_role_centric_workspace_content_markers_present(self):
        self.assertIn("Organization Overview", self.html)
        self.assertIn("Validation Overview", self.html)
        self.assertIn("My Operational Day", self.html)
        self.assertIn("Executive Portfolio Overview", self.html)
        self.assertIn("Governance Narrative", self.html)
        self.assertIn("Project Delivery Pulse", self.html)
        self.assertIn("Validation Footprint", self.html)
        self.assertIn("Field Notifications", self.html)
        self.assertIn("Top Operational Signals", self.html)
        self.assertIn("Open validation view", self.html)
        self.assertIn("Open my workplan", self.html)
        self.assertIn("Open executive snapshot", self.html)

    def test_project_registry_foundation_ui_present(self):
        self.assertIn('data-view="project-config"', self.html)
        self.assertIn("Project Configuration Studio", self.html)
        self.assertIn('id="projectRegistrySummaryBox"', self.html)
        self.assertIn('id="projectRegistryTable"', self.html)
        self.assertIn('id="projectStepButtons"', self.html)
        self.assertIn('id="projectReviewBox"', self.html)
        self.assertIn('id="projectWorkspaceShellBox"', self.html)
        self.assertIn("function loadProjectRegistryStudio", self.html)
        self.assertIn("function saveProjectStudioRecord", self.html)
        self.assertIn("function runProjectRegistryAction", self.html)
        self.assertIn("function publishProjectFromStudio", self.html)
        self.assertIn("function validateProjectStudioPayload", self.html)
        self.assertIn("function projectAssignmentRoleLabel", self.html)
        self.assertIn("function projectRegistryActionLabel", self.html)
        self.assertIn('callApi("/v1/admin/projects"', self.html)
        self.assertIn('/v1/admin/projects/${encodeURIComponent(projectId)}/${actionRoute}', self.html)
        self.assertIn('document.getElementById("projectRegistryTable").addEventListener("click"', self.html)
        self.assertIn("Project publication requires at least one province", self.python_source)
        self.assertIn("Project publication requires at least one district", self.python_source)
        self.assertIn("Project publication requires at least one assigned project team member.", self.python_source)

    def test_permission_engine_and_adaptive_workspace_present(self):
        self.assertIn("permissionContext: null,", self.html)
        self.assertIn("const PERMISSION_CATALOG = {", self.html)
        self.assertIn("const ROLE_PERMISSION_TEMPLATES = {", self.html)
        self.assertIn("const NAV_VIEW_CONFIG = [", self.html)
        self.assertIn("function normalizePermissionId", self.html)
        self.assertIn("function normalizePermissionList", self.html)
        self.assertIn("function roleTemplatePermissions", self.html)
        self.assertIn("function buildPermissionContext", self.html)
        self.assertIn("function syncPermissionContext", self.html)
        self.assertIn("function currentPermissionContext", self.html)
        self.assertIn("function activePermissionSet", self.html)
        self.assertIn("function actualPermissionSet", self.html)
        self.assertIn("function hasPermission", self.html)
        self.assertIn("function hasAnyPermission", self.html)
        self.assertIn("function hasAllPermissions", self.html)
        self.assertIn("function hasRequestPermission", self.html)
        self.assertIn("function hasAnyRequestPermission", self.html)
        self.assertIn("function hasAllRequestPermissions", self.html)
        self.assertIn("function canAccessView", self.html)
        self.assertIn("function preferredAccessibleView", self.html)
        self.assertIn("function renderAdaptiveNavigation", self.html)
        self.assertIn('if (!hasPermission("ASSIGN_TASKS")) {', self.html)
        self.assertIn('const canValidate = hasPermission("VALIDATE_EVIDENCE");', self.html)
        self.assertIn('const canApprove = hasPermission("APPROVE_TASKS");', self.html)
        self.assertIn('if (!hasPermission("VIEW_DATA_QUALITY")) {', self.html)
        self.assertIn('if (!hasAnyRequestPermission(["MANAGE_NOTIFICATIONS", "WORKSPACE_ADMIN"])) {', self.html)
        self.assertIn("permissions: Object.keys(PERMISSION_CATALOG),", self.html)
        self.assertIn('setActiveView(state.currentView || preferredAccessibleView(), { syncPresentation: false, silent: true });', self.html)
        self.assertIn("ROLE_PERMISSION_TEMPLATES = {", self.python_source)
        self.assertIn("def role_permissions(role: Optional[str]) -> List[str]:", self.python_source)
        self.assertIn("def effective_permissions(user: Optional[UserAccount]) -> List[str]:", self.python_source)
        self.assertIn("required_permission: Optional[str] = None,", self.python_source)
        self.assertIn("required_permissions: Optional[List[str]] = None,", self.python_source)
        self.assertIn('required_permission="WORKSPACE_ADMIN"', self.python_source)
        self.assertIn('required_permission="MANAGE_USERS"', self.python_source)
        self.assertIn('required_permission="VIEW_AUDIT_LOG"', self.python_source)

    def test_role_first_loader_and_request_audit_helpers_present(self):
        self.assertIn("requestAudit: [],", self.html)
        self.assertIn("function resetRequestAudit", self.html)
        self.assertIn("function recordRequestAudit", self.html)
        self.assertIn("function forbiddenRequestAudit", self.html)
        self.assertIn("function requestAuditSummary", self.html)
        self.assertIn("function shouldLoadDatasetWorkbench", self.html)
        self.assertIn("function buildWorkspaceLoadPlan", self.html)
        self.assertIn("function hydrateCurrentRoleWorkspace", self.html)
        self.assertIn("resetRequestAudit(`${currentPermissionContext().actualRoleId || sessionOperationalRoleId()}:${state.currentView || \"overview\"}`);", self.html)
        self.assertIn("await hydrateCurrentRoleWorkspace(state.currentView || preferredAccessibleView(), { resetAudit: false });", self.html)
        self.assertIn('audit: { page: viewId, module: "workspace_overview" }', self.html)
        self.assertIn('audit: { page: viewId, module: "project_workplan" }', self.html)
        self.assertIn('audit: { page: state.currentView, module: "narrative_summary_action" }', self.html)
        self.assertIn('audit: { page: state.currentView, module: "report_preview_action" }', self.html)

    def test_role_integrity_metrics_and_actions_use_hydrated_authorized_sources(self):
        project_hydration = self.html.split("state.projectWorkplan = canViewWorkplan ? workplan : null;", 1)[1].split("async function loadDataQualityOverview", 1)[0]
        sidebar_helper = self.html.split("function renderSidebarStatusCounters", 1)[1].split("function rerenderLocalizedViews", 1)[0]
        inbox_builder = self.html.split("function buildOperationalInboxItems", 1)[1].split("function renderHomeOperationalExperience", 1)[0]
        task_actions = self.html.split("function taskWorkflowActionButtons", 1)[1].split("function operationalTaskCardHtml", 1)[0]

        self.assertIn("renderOverviewCards(state.workspace);", project_hydration)
        self.assertIn("state.projectRegistrySummary?.total", sidebar_helper)
        self.assertIn("toArray(state.users)", sidebar_helper)
        self.assertIn("toArray(state.teams)", sidebar_helper)
        self.assertIn('module: "project_registry_counts"', self.html)
        self.assertIn("state.dataQuality?.issue_count ?? workspace?.data_quality?.issue_count", self.html)
        self.assertIn("value: formatValue(model.qualityIssueCount)", self.html)
        self.assertIn("function taskRequiresMealReview", self.html)
        self.assertIn("tasks.filter(taskRequiresMealReview)", inbox_builder)
        self.assertIn("No tasks are currently awaiting validation or evidence review.", self.html)
        self.assertIn("fieldUpdateScopeAllows", task_actions)
        self.assertIn('assigneeUsername === currentUsername', task_actions)

    def test_programme_manager_command_center_uses_real_portfolio_sources(self):
        self.assertIn('id="programmeManagerWorkspace"', self.html)
        self.assertIn('id="legacyOverviewWorkspace"', self.html)
        self.assertIn('id="pmKpiStrip"', self.html)
        self.assertIn('id="pmDeliveryChart"', self.html)
        self.assertIn('id="pmTaskStatusChart"', self.html)
        self.assertIn('id="pmDecisionsTable"', self.html)
        self.assertIn('id="pmRisksTable"', self.html)
        self.assertIn('id="pmPortfolioTrendChart"', self.html)
        self.assertIn('id="pmTeamWorkloadTable"', self.html)
        self.assertIn("function buildProgrammeManagerWorkspaceModel", self.html)
        self.assertIn("function renderProgrammeManagerWorkspace", self.html)
        self.assertIn("function programmeHorizontalBarChart", self.html)
        self.assertIn("function programmeLineChart", self.html)
        self.assertIn("async function loadProgrammeManagerPortfolioWorkplans", self.html)
        self.assertIn('/v1/demo/projects/${encodeURIComponent(projectId)}/workplan', self.html)
        self.assertIn('audit: { page: targetView, module: "programme_portfolio_workplan" }', self.html)
        self.assertIn("workspace?.portfolio?.delivery_health_avg_pct", self.html)
        self.assertIn("workspace?.portfolio?.reporting_confidence_avg_pct", self.html)
        self.assertIn("item.progress_mean_pct", self.html)
        self.assertIn("programmeTaskIsOverdue", self.html)
        self.assertIn("data-pm-task-id", self.html)
        self.assertIn('group: "overview"', self.html)
        self.assertIn('group: "delivery"', self.html)
        self.assertIn('group: "reporting"', self.html)
        self.assertIn('group: "projects"', self.html)
        self.assertIn("Alerts & Notifications", self.html)

    def test_programme_manager_visual_system_is_compact_and_responsive(self):
        pm_css = self.html.split("/* Programme Manager analytical workspace */", 1)[1].split("@media (max-width: 1560px)", 1)[0]

        self.assertIn("grid-template-columns: 220px minmax(0, 1fr);", pm_css)
        self.assertIn("--pm-navy: #0b1f3a;", pm_css)
        self.assertIn("--pm-blue: #175cd3;", pm_css)
        self.assertIn("font-size: 23px;", pm_css)
        self.assertIn("font-size: 28px;", pm_css)
        self.assertIn("border-radius: 6px;", pm_css)
        self.assertIn(".pm-chart-frame,", pm_css)
        self.assertIn("overflow-x: auto;", pm_css)
        self.assertIn(".pm-primary-analytics", pm_css)
        self.assertIn("grid-template-columns: minmax(0, 1.35fr) minmax(340px, 0.82fr);", pm_css)
        self.assertIn("@media (max-width: 1024px)", pm_css)
        self.assertIn("@media (max-width: 768px)", pm_css)
        self.assertIn("@media (max-width: 480px)", pm_css)
        self.assertNotIn("linear-gradient", pm_css)
        self.assertNotIn("overflow-x: hidden", pm_css)

    def test_programme_manager_portfolio_tables_prioritize_meaningful_columns_and_localize_copy(self):
        decision_renderer = self.html.split("function programmeDecisionTableHtml", 1)[1].split("function programmeRiskTableHtml", 1)[0]
        risk_renderer = self.html.split("function programmeRiskTableHtml", 1)[1].split("function programmeWorkloadTableHtml", 1)[0]
        portfolio_renderer = self.html.split("function renderProgrammeManagerWorkspace", 1)[1].split("async function openProgrammeManagerTask", 1)[0]

        self.assertIn('class="pm-data-table pm-decision-table"', decision_renderer)
        self.assertIn('class="pm-project-cell"', decision_renderer)
        self.assertIn('class="pm-description-cell"', decision_renderer)
        self.assertIn('class="pm-cell-primary pm-cell-clamp"', decision_renderer)
        self.assertIn('title="${escapeProgrammeHtml(item.project)}"', decision_renderer)
        self.assertIn('class="pm-data-table pm-risk-table"', risk_renderer)
        self.assertIn('title="${escapeProgrammeHtml(item.message)}"', risk_renderer)
        for marker in (
            "pmPortfolioEyebrow",
            "pmReportingContextLabel",
            "pmDeliveryNote",
            "pmTaskStatusNote",
            "pmDecisionsNote",
            "pmRisksNote",
            "pmTrendNote",
            "pmWorkloadNote",
        ):
            self.assertIn(marker, portfolio_renderer)
        self.assertIn("portfolioLoading = localizedCopy", portfolio_renderer)
        self.assertIn("workplansLoading = localizedCopy", portfolio_renderer)

    def test_programme_manager_workplan_uses_hydrated_tasks_and_canonical_drawer(self):
        workplan_model = self.html.split("function buildProgrammeManagerWorkplanModel", 1)[1].split("function programmeWorkplanFilteredTasks", 1)[0]
        workplan_renderer = self.html.split("function renderProgrammeManagerWorkplan", 1)[1].split("function renderProgrammeManagerWorkspace", 1)[0]
        drawer_renderer = self.html.split("function renderTaskDrawer", 1)[1].split("function currentOperationalProfile", 1)[0]

        self.assertIn('id="programmeManagerWorkplan"', self.html)
        self.assertIn('id="legacyWorkplanWorkspace"', self.html)
        self.assertIn('id="pmWorkplanKpis"', self.html)
        self.assertIn('id="pmWorkplanTable"', self.html)
        self.assertIn('id="pmDeliveryOwnerChart"', self.html)
        self.assertIn('id="pmUpcomingDeadlines"', self.html)
        self.assertIn("const tasks = toArray(workplan?.tasks);", workplan_model)
        self.assertIn("programmeTaskIsOverdue", workplan_model)
        self.assertIn("task.evidence_count", self.html)
        self.assertIn("programmeWorkplanTableHtml(visibleTasks)", workplan_renderer)
        self.assertIn("programmeHorizontalBarChart(model.owners.map", workplan_renderer)
        self.assertIn("programmeUpcomingDeadlinesHtml(model.deadlines)", workplan_renderer)
        self.assertIn('data-pm-workplan-task', self.html)
        self.assertIn("openTaskDrawer(trigger.dataset.pmWorkplanTask", self.html)
        self.assertIn("const programmeManager = isProgrammeManagerSession();", drawer_renderer)
        self.assertIn("programmeManagerActions = programmeManager ? taskWorkflowActionButtons(task)", drawer_renderer)
        self.assertIn('data-task-progress="${textSafe(task.task_id)}"', drawer_renderer)
        self.assertIn("handleTaskWorkflowAction(taskAction.dataset.taskAction", self.html)

    def test_programme_manager_workplan_is_role_isolated_and_width_bounded(self):
        shell_sync = self.html.split("function syncProgrammeManagerShell", 1)[1].split("function renderSidebarStatusCounters", 1)[0]
        pm_css = self.html.split("/* Programme Manager analytical workspace */", 1)[1].split("@media (max-width: 1560px)", 1)[0]

        self.assertIn('programmeWorkplan.classList.toggle("hidden", !active)', shell_sync)
        self.assertIn('legacyWorkplan.classList.toggle("hidden", active)', shell_sync)
        self.assertIn("targetComposerMount.appendChild(taskComposer)", shell_sync)
        self.assertIn(".pm-data-table.pm-workplan-table", pm_css)
        self.assertIn("min-width: 1030px;", pm_css)
        self.assertIn(".pm-workplan-filterbar", pm_css)
        self.assertIn(".pm-workplan-secondary", pm_css)
        self.assertIn(".pm-compact-empty", pm_css)
        self.assertIn('.app-root[data-active-view="workplan"] .app-shell.role-programme-manager .topbar > div:first-child', pm_css)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr));", pm_css)
        self.assertIn("overflow-x: auto;", pm_css)
        self.assertNotIn("body { overflow-x: hidden;", self.html)

    def test_programme_manager_tables_use_compact_badges_and_attention_semantics(self):
        pm_css = self.html.split("/* Programme Manager analytical workspace */", 1)[1].split("@media (max-width: 1560px)", 1)[0]
        badge_css = pm_css.split(".pm-status-badge {", 1)[1].split("}", 1)[0]
        decision_renderer = self.html.split("function programmeDecisionTableHtml", 1)[1].split("function programmeRiskTableHtml", 1)[0]
        risk_renderer = self.html.split("function programmeRiskTableHtml", 1)[1].split("function programmeWorkloadTableHtml", 1)[0]

        font_size = float(re.search(r"font-size:\s*([0-9.]+)px", badge_css).group(1))
        vertical_padding = float(re.search(r"padding:\s*([0-9.]+)px", badge_css).group(1))
        self.assertLessEqual(font_size, 11.5)
        self.assertLessEqual(vertical_padding, 4)
        self.assertIn("white-space: nowrap;", badge_css)
        self.assertIn('localizedCopy({ EN: "Attention", PT: "Atencao", FR: "Attention" })', decision_renderer)
        self.assertIn('localizedCopy({ EN: "Severity", PT: "Severidade", FR: "Severite" })', decision_renderer)
        self.assertIn('localizedCopy({ EN: "Severity", PT: "Severidade", FR: "Severite" })', risk_renderer)
        self.assertIn('<col style="width:282px">', decision_renderer)
        self.assertIn('<col style="width:210px">', risk_renderer)

    def test_programme_manager_charts_use_explicit_plot_geometry_and_wrapped_labels(self):
        chart_renderer = self.html.split("function programmeHorizontalBarChart", 1)[1].split("function programmeLineChart", 1)[0]
        portfolio_renderer = self.html.split("function renderProgrammeManagerWorkspace", 1)[1].split("async function openProgrammeManagerTask", 1)[0]

        self.assertIn("function programmeChartLabelLines", self.html)
        self.assertIn("options.labelWidth || 224", chart_renderer)
        self.assertIn("options.labelMaxLines || 1", chart_renderer)
        self.assertIn('<tspan x=', chart_renderer)
        self.assertIn("labelWidth: 292", portfolio_renderer)
        self.assertIn("labelMaxLines: 2", portfolio_renderer)
        self.assertIn("width: 440", portfolio_renderer)
        self.assertIn("rowHeight: 36", portfolio_renderer)
        self.assertIn("#pmTaskStatusChart svg", pm_css := self.html.split("/* Programme Manager analytical workspace */", 1)[1].split("@media (max-width: 1560px)", 1)[0])
        self.assertIn("width: min(100%, 520px);", pm_css)

    def test_programme_manager_drawer_uses_compact_inspector_and_canonical_permissions(self):
        drawer_helper = self.html.split("function programmeManagerTaskDrawerHtml", 1)[1].split("function renderTaskDrawer", 1)[0]
        drawer_renderer = self.html.split("function renderTaskDrawer", 1)[1].split("function currentOperationalProfile", 1)[0]
        action_helper = self.html.split("function taskWorkflowActionButtons", 1)[1].split("function operationalTaskCardHtml", 1)[0]
        pm_css = self.html.split("/* Programme Manager analytical workspace */", 1)[1].split("@media (max-width: 1560px)", 1)[0]

        for marker in (
            'class="pm-task-summary-strip"',
            'class="pm-task-details"',
            'class="pm-drawer-form"',
            'class="pm-drawer-actions"',
            'class="pm-drawer-subsection"',
        ):
            self.assertIn(marker, drawer_helper)
        self.assertIn("programmeManager ? taskWorkflowActionButtons(task)", drawer_renderer)
        self.assertIn("programmeManagerTaskDrawerHtml(task, approval, escalation, timeline, progressValue, tone, programmeManagerActions)", drawer_renderer)
        self.assertIn('shell.classList.toggle("pm-task-drawer", programmeManager)', drawer_renderer)
        self.assertIn('data-task-progress="${escapeProgrammeHtml(taskId)}"', drawer_helper)
        self.assertIn('data-task-evidence="${escapeProgrammeHtml(taskId)}"', drawer_helper)
        self.assertIn('data-task-comment="${escapeProgrammeHtml(taskId)}"', drawer_helper)
        self.assertIn('hasPermission("APPROVE_TASKS")', action_helper)
        self.assertIn('hasPermission("VALIDATE_EVIDENCE")', action_helper)
        self.assertIn('profile.id !== "field_coordinator"', action_helper)
        self.assertIn("width: min(640px, 100%);", pm_css)
        self.assertIn("height: 100dvh;", pm_css)
        self.assertIn(".task-drawer-shell.pm-task-drawer.hidden", pm_css)
        self.assertIn(".app-shell.role-programme-manager .pm-task-drawer .task-drawer-backdrop", pm_css)

    def test_primary_shell_uses_document_scroll_model(self):
        app_shell_css = self.html.split('    .app-shell {', 1)[1].split('    }', 1)[0]
        workspace_css = self.html.split('    .workspace-shell {', 1)[1].split('    }', 1)[0]
        shell_tail = self.html.split('    .workspace-shell {', 1)[1]
        content_shell_css = shell_tail.split('    .content-shell {', 1)[1].split('    }', 1)[0]
        topbar_css = shell_tail.split('    .topbar {', 1)[1].split('    }', 1)[0]
        topbar_controls_css = shell_tail.split('    .topbar-controls {', 1)[1].split('    }', 1)[0]

        self.assertIn('width: 100%;', app_shell_css)
        self.assertIn('min-width: 0;', app_shell_css)
        self.assertIn('grid-auto-rows: max-content;', workspace_css)
        self.assertNotIn('grid-template-rows:', workspace_css)
        self.assertIn('min-width: 0;', content_shell_css)
        self.assertIn('position: static;', topbar_css)
        self.assertIn('flex-wrap: wrap;', topbar_css)
        self.assertIn('min-width: 0;', topbar_css)
        self.assertNotIn('position: sticky;', topbar_css)
        self.assertNotIn('z-index:', topbar_css)
        self.assertIn('max-width: 100%;', topbar_controls_css)
        self.assertIn('min-width: 0;', topbar_controls_css)
        self.assertIn('flex: 1 1 440px;', topbar_controls_css)
        self.assertIn('.view :where(.panel, .stack, .list, [class*="-grid"], [class*="-shell"], .two-up, .three-up, .inline, .triple)', self.html)
        self.assertIn('.view :where(.subtle, .panel-note, .list, .pill, .badge, code, pre, td, th)', self.html)
        self.assertNotIn('body { overflow-x: hidden;', self.html)

    def test_collapsed_shell_resets_sidebar_scroll_constraints(self):
        tablet_css = self.html.split('@media (max-width: 1024px)', 1)[1].split('@media (max-width: 920px)', 1)[0]

        self.assertIn('.sidebar {', tablet_css)
        self.assertIn('position: static;', tablet_css)
        self.assertIn('top: auto;', tablet_css)
        self.assertIn('max-height: none;', tablet_css)
        self.assertIn('height: auto;', tablet_css)
        self.assertIn('overflow: visible;', tablet_css)
        self.assertIn('overflow-y: visible;', tablet_css)

    def test_admin_and_control_grids_collapse_before_fields_are_cramped(self):
        compact_css = self.html.split('@media (max-width: 1360px)', 1)[1].split('@media (max-width: 1240px)', 1)[0]
        table_shell_css = self.html.split('    .table-shell {', 1)[1].split('    }', 1)[0]
        audit_css = self.html.split('    .audit-row {', 1)[1].split('    }', 1)[0]

        self.assertIn('.admin-grid,', compact_css)
        self.assertIn('.project-config-grid,', compact_css)
        self.assertIn('.project-registry-toolbar {', compact_css)
        self.assertIn('grid-template-columns: 1fr;', compact_css)
        self.assertIn('repeat(auto-fit, minmax(min(220px, 100%), 1fr))', self.html)
        self.assertIn('.topbar-filters > div {', self.html)
        self.assertIn('overflow-x: auto;', table_shell_css)
        self.assertIn('min-width: 0;', audit_css)
        self.assertIn('.audit-row .subtle {', self.html)
        self.assertIn('overflow-wrap: anywhere;', self.html)

    def test_visible_view_headings_are_not_clipped(self):
        clipped_heading_selector = '.view > .panel:first-child > .panel-head > div > h2 {'
        self.assertNotIn(clipped_heading_selector, self.html)
        self.assertNotIn('clip: rect(0, 0, 0, 0);', self.html)

    def test_administration_workspace_ui_present(self):
        self.assertIn('id="saveOrganizationBtn"', self.html)
        self.assertIn('id="orgNameInput"', self.html)
        self.assertIn('id="orgCountryInput"', self.html)
        self.assertIn('id="orgTimezoneInput"', self.html)
        self.assertIn('id="orgLanguageInput"', self.html)
        self.assertIn('id="orgPlanInput"', self.html)
        self.assertIn('id="orgContactEmailInput"', self.html)
        self.assertIn('id="orgContactPersonInput"', self.html)
        self.assertIn('id="orgLogoPlaceholderInput"', self.html)
        self.assertIn('id="newUserTeam"', self.html)
        self.assertIn('id="newUserStatus"', self.html)
        self.assertIn('id="resetUserFormBtn"', self.html)
        self.assertIn('id="teamNameInput"', self.html)
        self.assertIn('id="teamLeadInput"', self.html)
        self.assertIn('id="teamMemberIdsInput"', self.html)
        self.assertIn('id="saveTeamBtn"', self.html)
        self.assertIn('id="teamList"', self.html)
        self.assertIn('id="permissionMatrixBox"', self.html)
        self.assertIn('id="auditActionFilter"', self.html)
        self.assertIn('id="auditActorFilter"', self.html)
        self.assertIn('id="auditDateFrom"', self.html)
        self.assertIn('id="auditDateTo"', self.html)
        self.assertIn('id="auditSearchInput"', self.html)
        self.assertIn('id="refreshAuditBtn"', self.html)
        self.assertIn("function renderOrganizationProfile", self.html)
        self.assertIn("function renderTeams", self.html)
        self.assertIn("function renderPermissionsMatrix", self.html)
        self.assertIn("function resetUserForm", self.html)
        self.assertIn("function resetTeamForm", self.html)
        self.assertIn('await callApi("/v1/admin/organization"', self.html)
        self.assertIn('await callApi(editingUserId ? `/v1/admin/users/${encodeURIComponent(editingUserId)}` : "/v1/admin/users"', self.html)
        self.assertIn('await callApi(editingTeamId ? `/v1/admin/teams/${encodeURIComponent(editingTeamId)}` : "/v1/admin/teams"', self.html)
        self.assertIn('await callApi(`/v1/admin/audit?${query.toString()}`', self.html)


if __name__ == "__main__":
    unittest.main()
